# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/17149/Documents/CECS361_GroupProject/CECS361_GroupProject.cache/wt [current_project]
set_property parent.project_path C:/Users/17149/Documents/CECS361_GroupProject/CECS361_GroupProject.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
set_property ip_output_repo c:/Users/17149/Documents/CECS361_GroupProject/CECS361_GroupProject.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/17149/Documents/CECS361_GroupProject/ALU_rio.v
  C:/Users/17149/Documents/CECS361_GroupProject/sseg_sources/Counter.v
  C:/Users/17149/Documents/CECS361_GroupProject/Memory_Controller.v
  C:/Users/17149/Documents/CECS361_GroupProject/sseg_sources/anode_selector.v
  C:/Users/17149/Documents/CECS361_GroupProject/CECS361_GroupProject.srcs/sources_1/new/debounce.v
  C:/Users/17149/Documents/CECS361_GroupProject/sseg_sources/hex_to_sseg.v
  C:/Users/17149/Documents/CECS361_GroupProject/CECS361_GroupProject.srcs/sources_1/new/memory2.v
  C:/Users/17149/Documents/CECS361_GroupProject/sseg_sources/rotate_gen.v
  C:/Users/17149/Documents/CECS361_GroupProject/sseg_sources/top_level_sseg.v
  C:/Users/17149/Documents/CECS361_GroupProject/Top_level.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/17149/Documents/CECS361_GroupProject/NexysA7-100t.xdc
set_property used_in_implementation false [get_files C:/Users/17149/Documents/CECS361_GroupProject/NexysA7-100t.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Top_level -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_level.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_level_utilization_synth.rpt -pb Top_level_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
